- name: Search DCE Kconfig
        run: |
          echo "============================================================"
          echo "SEARCH: LD_DEAD_CODE_DATA_ELIMINATION"
          echo "============================================================"

          grep -Rns \
            "LD_DEAD_CODE_DATA_ELIMINATION" \
            arch/arm64 \
            arch/Kconfig \
            || true
